[[openfhe_julia]]
arch = "aarch64"
git-tree-sha1 = "49ca4c9e7862fca81823b9665221b54c4b2811c1"
julia_version = "1.10.0"
os = "macos"

    [[openfhe_julia.download]]
    sha256 = "55096ca7b58eedc8d0871a8537b4a1a853d85d0a12b81a3c97ba7a0ffc86f456"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.4.0+0/openfhe_julia.v0.4.0.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[openfhe_julia]]
arch = "aarch64"
git-tree-sha1 = "215e8a8d5fbd0bda209e7240dea280746e978398"
julia_version = "1.11.1"
os = "macos"

    [[openfhe_julia.download]]
    sha256 = "1455f9871c369b0bbccc2c793001b1adaa26424ddd246dbc90c0b35a42da9695"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.4.0+0/openfhe_julia.v0.4.0.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[openfhe_julia]]
arch = "aarch64"
git-tree-sha1 = "67194627c8115967147667e45de218a4ab5f1f4a"
julia_version = "1.12.0"
os = "macos"

    [[openfhe_julia.download]]
    sha256 = "3ca111699d8608c2b954d5405ae70cd99fec93060636d0feedbc8868e0095989"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.4.0+0/openfhe_julia.v0.4.0.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[openfhe_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27f19955869d0786b21082daeb764dd54dd70e9c"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia.download]]
    sha256 = "49d8d4b8d439872dc47799105ce4f1e1b5637173678264610bbfa32c96615f9e"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.4.0+0/openfhe_julia.v0.4.0.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[openfhe_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e246e463fada256e256dd42b40c64fd5f1d93383"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[openfhe_julia.download]]
    sha256 = "03c430140bc64b608583e063e80417f48645460c5562518f562e5ed6ec4b9310"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.4.0+0/openfhe_julia.v0.4.0.aarch64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[openfhe_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abba04eae612eb51f4e7eab68eaaaab192fd420f"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia.download]]
    sha256 = "659cac464aada09f00c1567d31c0735ff771df9608563c12e9ae9192c25ed1d3"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.4.0+0/openfhe_julia.v0.4.0.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
git-tree-sha1 = "bc523555890d6dceea403af184f968f5479e90a6"
julia_version = "1.10.0"
os = "macos"

    [[openfhe_julia.download]]
    sha256 = "2c9efa482122f2f10a52b54c51b39e3b5f16bb8f75628b81029d90727c6fcdf5"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.4.0+0/openfhe_julia.v0.4.0.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
git-tree-sha1 = "e83b43256b0dad60080c0e7994ad7291bdfede49"
julia_version = "1.11.1"
os = "macos"

    [[openfhe_julia.download]]
    sha256 = "ff61bf5a932304f7bc43cdc8421008356b6af031346864e905c177442827e2b8"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.4.0+0/openfhe_julia.v0.4.0.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
git-tree-sha1 = "f62c06a244bb16c03491f053bb33ff4367d4022e"
julia_version = "1.12.0"
os = "macos"

    [[openfhe_julia.download]]
    sha256 = "494a2abd31f73973ae61b3af53ff2450f5539337b8ec9e3c354e75d9423d2013"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.4.0+0/openfhe_julia.v0.4.0.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dec0f2d5ddf99ef369be82505a551832ec5f7c6c"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia.download]]
    sha256 = "5095771afdeba3abc4c2a9946486b013f98fd13d4197a8252573ac9fd194b1da"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.4.0+0/openfhe_julia.v0.4.0.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "026ad469cd4b6bb463d889939e95b171c2765f6e"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[openfhe_julia.download]]
    sha256 = "e85714bd7167896f0eae78d1991c734f72076f62d80a1ed9296ad7d82f7a3a57"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.4.0+0/openfhe_julia.v0.4.0.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd19f510ab3a5cdede4e30b170d6ea3d90ad37b1"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[openfhe_julia.download]]
    sha256 = "6971d8f66f5fed2266f0afa766635ef4a0063af3824d2e40af29c6cfc96bb46d"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.4.0+0/openfhe_julia.v0.4.0.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
git-tree-sha1 = "bfc4d2fb72dc1ad13361fa67ce2ac91605f12031"
julia_version = "1.10.0"
os = "freebsd"

    [[openfhe_julia.download]]
    sha256 = "743d8af918ebd6b64e279acb87843671c8fe5a5c952d875876ba57e9d69840f5"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.4.0+0/openfhe_julia.v0.4.0.x86_64-unknown-freebsd-julia_version+1.10.0.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
git-tree-sha1 = "aec5d0941f6777bda53b106d642cb4c7e471f3e9"
julia_version = "1.11.1"
os = "freebsd"

    [[openfhe_julia.download]]
    sha256 = "c30f0d2c5de19117120ddb137348ca0d3e836de5e069a1644109d11dcb141c68"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.4.0+0/openfhe_julia.v0.4.0.x86_64-unknown-freebsd-julia_version+1.11.1.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
git-tree-sha1 = "107c2bceee203785edbb392a7ff5ab36722c3421"
julia_version = "1.12.0"
os = "freebsd"

    [[openfhe_julia.download]]
    sha256 = "3b191160a8eefc8f3e6194d594cb5a7f3d9f5c2cdeab3d106fc83e10d31c04a9"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.4.0+0/openfhe_julia.v0.4.0.x86_64-unknown-freebsd-julia_version+1.12.0.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06241d9f11005da8d786482869eba14cd536c82c"
julia_version = "1.10.0"
os = "windows"

    [[openfhe_julia.download]]
    sha256 = "952ac7fa4004d3d996637a1db579ab7a20454f05cbfd1bd1bee3264bc14709b8"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.4.0+0/openfhe_julia.v0.4.0.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4af1628ba9074cc81d3631fc1478957def1a9fff"
julia_version = "1.11.1"
os = "windows"

    [[openfhe_julia.download]]
    sha256 = "40360550dcdc772aba76432b07153e562b4512cded61f4ac2b7c88f6deeaabc3"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.4.0+0/openfhe_julia.v0.4.0.x86_64-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
[[openfhe_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c388dc6a3b84d32f67353cb0609b564f86b75012"
julia_version = "1.12.0"
os = "windows"

    [[openfhe_julia.download]]
    sha256 = "95db6e2178be91d745ac71c3d28484625df73ce0407998fe6c70f1f7d8c7c056"
    url = "https://github.com/JuliaBinaryWrappers/openfhe_julia_jll.jl/releases/download/openfhe_julia-v0.4.0+0/openfhe_julia.v0.4.0.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
